plugins {
    id "com.android.library"
}

android {
    namespace "com.foodaicamera.plugin"
    compileSdk 36

    defaultConfig {
        minSdk 23
        consumerProguardFiles "consumer-rules.pro"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly files("../../../android/build/libs/release/godot-lib.template_release.aar")
    implementation "androidx.core:core:1.13.1"
    implementation "androidx.annotation:annotation:1.8.2"
}
