## 도트(픽셀아트) 데이터 — 팔레트 + 스프라이트 (카드 3 · 캐릭터 · 보스 3)
extends RefCounted

const PAL := {
	"K": Color("241b2e"), "W": Color("f5f5f5"),
	"R": Color("d1495b"), "r": Color("8f2d3b"),
	"O": Color("e8873b"),
	"Y": Color("f2c14e"), "y": Color("ffe0a0"),
	"G": Color("5bb87a"), "g": Color("357a4b"),
	"B": Color("5b8fd1"), "b": Color("37578f"),
	"P": Color("f4a7c0"), "p": Color("d76b93"),
	"N": Color("9a6531"), "n": Color("5e3d1c"),
	"S": Color("e8b48a"), "C": Color("5fc9c9"),
	"D": Color("9aa4b0"), "d": Color("5a6472"),
}

static func icon(name: String) -> Array:
	return ICONS.get(name, [])

const ICONS := {
	# ── 카드 3종
	"candy": [
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"...............KK...............",
		"K...........KKKKKKKK............",
		"K.........KKppppppppKK..........",
		"KK.......KKppppPPppppKK........K",
		"KpK.....KKppWPPPPPPPppKK......Kp",
		"KppK....KppWWWPWPWPPPppK.....Kpp",
		"KPppK..KppWWWWWPPPPPPPppK...KppP",
		"KPPppK.KppPWWWPPPPPWPPppK..KppPP",
		"KPPPppKKppPPWPPPPPPPPPppK.KppPPP",
		"KPPPPpKKpPPPWPPPPWPPPPPpKKppPPPP",
		"KPPPPPKKpPPPPPPPPWPPPPPpKKpPPPPP",
		"KPPPPppKppPPWPPPWPPPPPppKKppPPPP",
		"KPPPppKKppPPPPWWPPPPPPppK.KppPPP",
		"KPPppK.KppPPPPPPPPPPPPppK..KppPP",
		"KPppK...KppPPPPPPPPPPppK....KppP",
		"KppK....KKppPPPPPPPPppKK.....Kpp",
		"KpK......KKppppPPppppKK.......Kp",
		"KK........KKppppppppKK.........K",
		"K...........KKKKKKKK............",
		"K..............KK...............",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
	],
	"shaker": [
		"................................",
		"................................",
		"...........KKKKKKKKKK...........",
		"...........KDDDDDDDDK...........",
		"..........KDDDDDDDDDDK..........",
		"..........KddddddddddK..........",
		"..........KddddddddddK..........",
		".........KKddddddddddKK.........",
		"........KDDDDDDDDDDDDDDK........",
		"........KddddddddddddddK........",
		"........KDDDDDDDDDDDDDDK........",
		"........KWWBBBBBBBBBbbbK........",
		"........KWWBBBBBBBBBbbbK........",
		".......KWWWBBBBBBBBBbbbbK.......",
		".......KWWWBBBBBBBBBbbbbK.......",
		".......KWWWBBBBBBBBBbbbbK.......",
		".......KWWWBBBBBBWWWbbbbK.......",
		".......KWWWBBBBBBBBBbbbbK.......",
		".......KWWWBBBBBBBBBbbbbK.......",
		".......KWWWBBBBBBBBBbbbbK.......",
		".......KWWWBBBBBBWWWbbbbK.......",
		".......KWWWBBBBBBBBBbbbbK.......",
		".......KWWWBBBBBBBBBbbbbK.......",
		".......KWWWBBBBBBBBBbbbbK.......",
		".......KWWWBBBBBBWWWbbbbK.......",
		".......KWWWBBBBBBBBBbbbbK.......",
		".......KWWWBBBBBBBBBbbbbK.......",
		".......KWWWBBBBBBBBBbbbbK.......",
		"........KWWBBBBBBBBBbbbK........",
		"........KWWBBBBBBBBBbbbK........",
		".........KKKKKKKKKKKKKK.........",
		"................................",
	],
	"shield": [
		"................................",
		"................................",
		".....KKKKKKKKKKKKKKKKKKKKKK.....",
		"....KggggggggggggggggggggggK....",
		"....KggGGGGGGGGGGGGGGGGGGggK....",
		"....KggGGGGGGGGGGGGGGGGGGggK....",
		"....KggGGGGGGGGGGGGGGGGGGggK....",
		"....KggGGGGGGGGGGGGGGGGGGggK....",
		"....KggGGGGGGGGGGGGGGGGGGggK....",
		"....KggGGGGGGGGGGGGGGGGGGggK....",
		"....KggGGGGGGGGKKGGGGGGGGggK....",
		"....KggGGGGGGGKKKKGGGGGGGggK....",
		"....KggGGGGGGKKyyKKGGGGGGggK....",
		"....KggGGGGGKKyyyyKKGGGGGggK....",
		"....KggGGGGKKyyyyyyKKGGGGggK....",
		"....KggGGGGKKyyyYYYKKGGGGggK....",
		"....KggGGGGGKKyyYYKKGGGGGggK....",
		".....KggGGGGGKKyYKKGGGGGggK.....",
		".....KggGGGGGGKKKKGGGGGGggK.....",
		".....KggGGGGGGGKKGGGGGGGggK.....",
		"......KggGGGGGGGGGGGGGGggK......",
		"......KggGGGGGGGGGGGGGGggK......",
		"......KggGGGGGGGGGGGGGGggK......",
		".......KggGGGGGGGGGGGGggK.......",
		".......KggGGGGGGGGGGGGggK.......",
		"........KggGGGGGGGGGGggK........",
		".........KggGGGGGGGGggK.........",
		"..........KggGGGGGGggK..........",
		"...........KggggggggK...........",
		"............KKKKKKKK............",
		"................................",
		"................................",
	],
	# ── 플레이어 캐릭터
	"hero": [
		"..................",
		".....KKKKKKK......",
		"...KKGGGGGGGKK....",
		"..KGGGGGGGGGGGK...",
		"..KRRRRRRRRRRRK...",
		"..KRRRRRRRRRRRK...",
		"..KGGGGGGGGGGGK...",
		".KGGKKGGGGKKGGK...",
		".KGGKKGGGGKKGGK...",
		".KGGGGGGGGGGGGK...",
		".KGGGGGGGGGGGGK...",
		".KGGGWWWWWWGGGK...",
		".KGGGGGGGGGGGGK...",
		"..KGGGGGGGGGGK....",
		"...KKGGGGGGKK.....",
		".....KKKKKK......",
		"..................",
		"..................",
	],
	# ── 보스: 메가 버거 타이탄 (왕관 + 성난 패티 + 벨트)
	"burger": [
		"......KYKYKYK.......",
		"......KYYYYYK.......",
		"......OKKKKKO.......",
		"....KKNNNNNNNNKK....",
		"...KNNNyNNyNNNNNK...",
		"...KNNNNNNNNNNNNK...",
		"...KGGGGGGGGGGGGK...",
		"..KKYYYYYYYYYYYYKK..",
		"..KnnnnnnnnnnnnnnK..",
		"..KnWRnnnnnnnnWRnK..",
		"..KnWRnnnnnnnnWRnK..",
		"..KnnnnnKKKKnnnnnK..",
		"..KnnnnnnnnnnnnnnK..",
		"..KYYYYYYYYYYYYYYK..",
		"..KnnnnnnnnnnnnnnK..",
		"..KNNNNNNNNNNNNNNK..",
		"..KKKKKKKKKKKKKKKK..",
		"..KKKKKKKYYKKKKKKK..",
		"...KNNNNNNNNNNNNK...",
		"....KKNNNNNNNNKK....",
		"......KKKKKKKK......",
		"...................",
	],
	# ── 보스: 슈가 퀸 (왕관 + 프릴 드레스 + 막대사탕)
	"sugar_queen": [
		"......KYKYKYK......",
		"......KYOYOYK......",
		"......OKKKKKO..KWK.",
		".....KPPPPPPPK.WpWK",
		"....KPPPPPPPPPKKWKK",
		"....KPRKPPPPRKPKnK.",
		"....KPPPPPPPPPPKnK.",
		"....KPPpPPPPpPPKnK.",
		"...KKPPPPPPPPPPKK..",
		"..KPPPPPPPPPPPPPPK.",
		"..KPPPWWPPPPWWPPPK.",
		"..KPPPPPPPPPPPPPPK.",
		"..KPpPPPPPPPPPPpPK.",
		"..KPPPWWPPPPWWPPPK.",
		"..KPPPPPPPPPPPPPPK.",
		"...KPPPPPPPPPPPPK..",
		"...KKPPPPPPPPPPKK..",
		".....KKKKKKKKKK....",
	],
	# ── 보스: 시저 샐러드 킹 (왕관 + 크루통 수염 + 포크)
	"salad_king": [
		".......KYKYKYK......D",
		".......KYOYOYK......D",
		".......OKKKKKO....DDDD",
		".....KGKGKGKGKGK....D",
		"....KGGGGGGGGGGGK...D",
		"...KGGRGGGGGGRGGGK..D",
		"...KGWKGGGGGGWKGGK..D",
		"...KGGGGGGGGGGGGGK..",
		"...KGGGgggygggGGGK..",
		"...KGGygggggggyGGK..",
		"...KGGGgggygggGGGK..",
		"..KRRRRRRRRRRRRRRRK.",
		"..KNnnnnnnnnnnnnnNK.",
		"..KNnnBnnnnnnBnnnNK.",
		"..KNnnnnnnnnnnnnnNK.",
		"...KNnnnnnnnnnnnNK..",
		"....KNNNNNNNNNNNK...",
		".....KKNNNNNNNKK....",
		".......KKKKKKK......",
	],
	# ── 보스 공격 투사체 (음식)
	"fries": [
		"...y.y.y.y..",
		"..KyKyKyKy..",
		"..yyyyyyyy..",
		".RRRRRRRRRR.",
		".RWRRRRRRRR.",
		".RRRRRRRRRR.",
		".RRRRRRRRRR.",
		"..RRRRRRRR..",
		"...RRRRRR...",
	],
	"cola": [
		"....WK.....",
		"....WK.....",
		"..RRRRRRR..",
		"..RWWWWRR..",
		"..RRRRRRR..",
		"..RRRRRRR..",
		"..RRRRRRR..",
		"...RRRRR...",
		"...RRRRR...",
	],
	"cheese": [
		"............",
		".KKKKKKKK...",
		".KYYYYYYK...",
		".KYOYYYYK...",
		".KYYYYOK....",
		".KYOYYK.....",
		".KYYYK......",
		".KYYK.......",
		".KYK........",
	],
	"lollipop": [
		"..KWK......",
		".KWpWK.....",
		".KpWpK.....",
		".KWpWK.....",
		"..KWK......",
		"...n.......",
		"...n.......",
		"...n.......",
		"...n.......",
	],
	"cake": [
		"....R......",
		"...KRK.....",
		".KKKKKKK...",
		".KWWWWWK...",
		".KPPPPPK...",
		".KnnnnnK...",
		".KPPPPK....",
		".KnnnK.....",
		".KPK.......",
	],
	"donut": [
		"..KKKKKK...",
		".KpPPPPpK..",
		".KPKKKKPK..",
		".KPK..KPK..",
		".KPKKKKPK..",
		".KpPPPPpK..",
		".KnnnnnnK..",
		"..KKKKKK...",
	],
	"cream": [
		"....WW.....",
		"...WWWW....",
		"..WWDWWW...",
		".WWWWWWWW..",
		".WWDWWWWW..",
		"..WWWWWW...",
		"...WWWW....",
		"....WW.....",
	],
	"fork": [
		".D.D.D.....",
		".D.D.D.....",
		".DDDDD.....",
		"...D.......",
		"...D.......",
		"...D.......",
		"...D.......",
		"...D.......",
		"...D.......",
	],
	"bacon": [
		"............",
		".KKKKKKKKK..",
		".KRRRRRRRK..",
		".KWWWWWWWK..",
		".KRRRRRRRK..",
		".KWWWWWWWK..",
		".KRRRRRRRK..",
		".KKKKKKKKK..",
	],
	"dressing": [
		"..W..W.....",
		".W.WW.W....",
		"..WWWW.....",
		".WWWWWW....",
		".WWDWWW....",
		"..WWWW.....",
		"...WW......",
		"..W..W.....",
	],
}

# 문자 그리드를 rect 안에 정수배로 크리스프하게 그림
static func draw_grid(ci: CanvasItem, rows: Array, palette: Dictionary, rect: Rect2, tint := Color(1, 1, 1, 1), override := Color(0, 0, 0, 0)) -> void:
	if rows.is_empty():
		return
	var cols := 0
	for r in rows:
		cols = max(cols, (r as String).length())
	var n := rows.size()
	if cols == 0 or n == 0:
		return
	var ps: float = floor(min(rect.size.x / float(cols), rect.size.y / float(n)))
	if ps < 1.0:
		ps = 1.0
	var ox: float = rect.position.x + floor((rect.size.x - ps * cols) * 0.5)
	var oy: float = rect.position.y + floor((rect.size.y - ps * n) * 0.5)
	for y in n:
		var line: String = rows[y]
		for x in line.length():
			var ch := line[x]
			if palette.has(ch):
				var col: Color = override if override.a > 0.0 else palette[ch] * tint
				ci.draw_rect(Rect2(ox + x * ps, oy + y * ps, ps, ps), col)
